Search by Category: unit tests
OlivierTD/team-rocket pull request #126
Opened 2018-03-30 18:48 UTC by SaiShan

User Story: #54 
Task: #114

2018-04-03 18:50 UTC, OlivierTD requested changes
Please review your tests thanks!

2018-04-18 05:51 UTC, davidlegare requested changes
You can't mock the fragment that you are testing, it beats the whole purpose of testing it, you just mock the dependencies.

2018-04-18 05:52 UTC, davidlegare commented
There are conflicts to resolve as well.

2018-04-19 01:09 UTC, SaiShan commented on app/src/test/java/categorySearchTest/CategorySearchTest.java
> +    public void builderTest() throws Exception{
From my research, this is the only kind of test that i have found for alert dialog. Other functions for this user story, such as the search, have the same issues as the centralized search.

2018-04-19 02:18 UTC, closed without merging