Tests for resetting stats
OlivierTD/team-rocket pull request #177
Opened 2018-04-18 05:53 UTC by vartanbeno

Instrumented test. Issue will be update to include the once this PR is merged to master.

2018-04-18 06:04 UTC, vartanbeno commented
Merge conflicts resolved

2018-04-18 15:22 UTC, OlivierTD requested changes

2018-04-18 17:05 UTC, vartanbeno commented on app/src/test/java/resetStatsTest/ResetStatsTest.java
> +        assertEquals(statisticsFragment.getResetStatsButton(), mockButton);
@OlivierTD After much consideration I believe there's no functionality that can be unit tested. I decided to take it out.

2018-04-18 17:25 UTC, anania-y approved these changes
Tests look good. Run well on my end.

2018-04-19 02:13 UTC, SaiShan commented
Tests are passing on my device too. Code which included the changes requested by @OlivierTD were removed.

Please wait for CircleCi to be done before merging.

2018-04-19 02:14 UTC, SaiShan approved these changes

2018-04-19 20:05 UTC, merged